Conference Page: Feature/capstone project
lucy-sees/HTML-CSS---JavaScript-capstone-project pull request #1
Opened 2023-08-02 21:02 UTC by lucy-sees

These are the implementations I made on this project:

- Used a medium-fidelity wireframe to create a UI.
- Followed written requirements (e.g. user stories).
- Used semantic HTML tags.
- Applied best practices in HTML code.
- Used CSS selectors correctly.
- Used CSS box model.
- Used Flexbox to place elements in the page.
- Used images and backgrounds to enhance the look of a website.
- Demonstrated ability to create UIs adaptable to different screen sizes using media queries.
- Used GitHub Pages to deploy web pages.
- Applied JavaScript best practices and language style guides in code.
- Used JavaScript to manipulate DOM elements.
- Used JavaScript events.
- Used objects to store and access data.

Kindly take your time to review my work.

2023-08-02 23:13 UTC, Strangeal requested changes
Hi @lucy-sees, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Alt Text](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Nice *UI* design ✅  
- Professional `README` template ✅ 
- Correct `GitHub` workflow ✅ 
- Meaningful **Github** commits ✅ 
- Correct `.github/workflows` for linters ✅ 
- Followed *best-practices* ✅ 
- Correct **Semantics** used ✅ 
- Well structured project ✅ 

## Required Changes ♻️
 - [ ] Great job building such an Impressive UI as your first capstone project. while you did a great job in implementing the project requirement I think you can improve the look of your project to look much better to improve user experience. 
 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-02 23:13 UTC, Strangeal commented on mobile.css
> +
- [ ] Great job building your hamburger menu, its functionalities are working `100%`, However, I think you can improve on its looks to help create a good user experience. Kindly consider the below suggestions to do just that:
   - [ ] When the `menu` is opened users are able to see some text of the main page which isn't the intended behavior. To fix this issue kindly add a `z-index` to your `nav-wrapper`. Adding a `z-index` will help control the stacking order of elements on the page, making sure that the navigation `menu` is brought to the foreground and effectively shadowing the background content.  
   - [ ] To create a better user experience I would suggest that you adjust the looks of your logo on the `menu` as it's currently looking misaligned. You can see your `logo` somewhere and so as your brand name.
   - [ ] Also, Your close `icon` is misaligned so kindly position it properly. To help improve the looks of your hamburger `menu` I have included a screenshot of my personal hamburger menu in my first capstone where I built this same project as a sample for you to look at, It might not be the best but it will guide you to get an idea on how to make yours look better. See below for more details:
  
 <table>
<tr>
<th align=“middle”>Sample design</th>
<th align=“middle”>Your design</th>
</tr>
<tr>
<td>
<img width="376" alt="Screenshot 2023-08-02 at 22 11 06" src="https://github.com/lucy-sees/HTML-CSS---JavaScript-capstone-project/assets/107192076/f6b64d1f-17a1-4441-82da-bb8142b54b5c">
</td>
<td><img width="376" alt="Screenshot 2023-08-02 at 21 44 18" src="https://github.com/lucy-sees/HTML-CSS---JavaScript-capstone-project/assets/107192076/dc2d644f-7b48-4718-9a12-f83ea11766f7"></td>
</tr>
</table>

2023-08-02 23:13 UTC, Strangeal commented on desktop.css
> +  }
- [ ] Great job building your nav and hero section, However, I think you can improve on its looks to help create a good user experience. Kindly consider the below suggestions to do just that:
   - [ ] To start from the nav, Your `logo` is misaligned as compared to that of the original design given in the project requirements. Looking at the original design you can see that the `logo` alignment aligns with the entire content of the page on the left. To make a better understanding kindly take a look at the screenshot below.
   - [ ] Also, the main `headline` text on your hero section has an excess `margin` on the left making it misalign comparing it to the original design.
   - [ ] As a final note, I would add that you kindly make sure that all content on your hero sections is aligned on the left equally as shown in the original design and also responsive on all screen sizes. See below for more details:
 <table>
<tr>
<th align=“middle”>Binance design</th>
<th align=“middle”>Your design</th>
</tr>
<tr>
<td>
<img width="959" alt="Screenshot 2023-08-02 at 22 38 45" src="https://github.com/lucy-sees/HTML-CSS---JavaScript-capstone-project/assets/107192076/04a3b169-5e3c-47ef-acb4-e2c2838d12c4">
</td>
<td>
<img width="1438" alt="Screenshot 2023-08-02 at 21 23 21" src="https://github.com/lucy-sees/HTML-CSS---JavaScript-capstone-project/assets/107192076/297bc9ae-cd0d-461f-88be-2f6401430cff">
</td>
</tr>
</table>

2023-08-02 23:13 UTC, Strangeal commented on mobile.css
> +
- [ ] Great job building the main program section, However, I think you can improve on its looks to help create a good user experience. Kindly consider the below suggestions to do just that:
   - [ ] Kindly consider aligning your main program section to have equal spacing on the left and right just like on other content on the page as shown in the original design.
   - [ ] Kindly adjust the gap you have between each card as it doesn't much that of the original design. See below for more details:

#### Desktop
<table>
<tr>
<th align=“middle”>Behance design</th>
<th align=“middle”>Your design</th>
</tr>
<tr>
<td>
<img width="958" alt="Screenshot 2023-08-02 at 21 45 35" src="https://github.com/lucy-sees/HTML-CSS---JavaScript-capstone-project/assets/107192076/835f6d99-2ab2-4d79-97ab-f658677c857f">
</td>
<td>
<img width="1438" alt="Screenshot 2023-08-02 at 21 31 42" src="https://github.com/lucy-sees/HTML-CSS---JavaScript-capstone-project/assets/107192076/de1a426b-e5a2-42c6-b75f-23c0507f5f89">
</td>
</tr>
</table>

 - [ ] On mobile devices your cards should be in a flex column direction to match that of the original design and also help create a better user experience. Currently, you can see from your design that during screen resize it doesn't respond to the flex column on mobile devices as intended so kindly consider fixing this issue. 
 - [ ] Also, Please make sure to style your button to match that of the original design.

#### Mobile
<table>
<tr>
<th align=“middle”>Behance design</th>
<th align=“middle”>Your design</th>
</tr>
<tr>
<td>
<img width="448" alt="Screenshot 2023-08-02 at 22 51 41" src="https://github.com/lucy-sees/HTML-CSS---JavaScript-capstone-project/assets/107192076/7993821d-9c97-4b02-8853-9d282c7598dd">
</td>
<td>
<img width="702" alt="Screenshot 2023-08-02 at 23 02 27" src="https://github.com/lucy-sees/HTML-CSS---JavaScript-capstone-project/assets/107192076/2a159147-28b8-4694-b44f-c38109df6cc4">

<img width="415" alt="Screenshot 2023-08-02 at 23 05 48" src="https://github.com/lucy-sees/HTML-CSS---JavaScript-capstone-project/assets/107192076/0952be81-e2c3-4836-aae6-4d3c4ce48456">

</td>
</tr>
</table>

2023-08-02 23:13 UTC, Strangeal commented on mobile.css
> +  }
- [ ] To improve the looks and feel of your website kindly consider adjusting the line below your text to match that of the original design as they're currently not. See below for more details:

<table>
<tr>
<th align=“middle”>Behance design</th>
<th align=“middle”>Your design</th>
</tr>
<tr>
<td>
<img width="331" alt="Screenshot 2023-08-02 at 21 45 53" src="https://github.com/lucy-sees/HTML-CSS---JavaScript-capstone-project/assets/107192076/52b423e5-ca1d-453f-9502-b614fc73021c">
</td>
<td>
<img width="430" alt="Screenshot 2023-08-02 at 21 38 20" src="https://github.com/lucy-sees/HTML-CSS---JavaScript-capstone-project/assets/107192076/5d72a4ce-8e68-4916-a212-c0f12cf7868c">
</td>
</tr>
</table>

2023-08-02 23:13 UTC, Strangeal commented on mobile.css
> +  }
- [ ] To improve the looks and feel of your website kindly consider adjusting the line below your text to match that of the original design as they're currently not. See below for more details:

<table>
<tr>
<th align=“middle”>Behance design</th>
<th align=“middle”>Your design</th>
</tr>
<tr>
<td>
<img width="331" alt="Screenshot 2023-08-02 at 21 46 03" src="https://github.com/lucy-sees/HTML-CSS---JavaScript-capstone-project/assets/107192076/ce620e26-9312-445c-a594-c11d8139dd51">
</td>
<td>
<img width="480" alt="Screenshot 2023-08-02 at 21 38 45" src="https://github.com/lucy-sees/HTML-CSS---JavaScript-capstone-project/assets/107192076/8ec02b25-14f7-4fa9-a160-508aabf84b8a">
</td>
</tr>
</table>

2023-08-02 23:23 UTC, Strangeal commented on about.html
> +     </div>
- [ ] Kindly consider removing the partner section from your About page as it doesn't match the original design.
<img width="1440" alt="Screenshot 2023-08-02 at 23 18 20" src="https://github.com/lucy-sees/HTML-CSS---JavaScript-capstone-project/assets/107192076/444aaaea-57af-45e8-97cf-d17e9cc32252">

2023-08-03 13:18 UTC, bienvenuushindi approved these changes
# Approved 👏  

## Hi @lucy-sees   👋, 

Well done implementing the requested changes 👏

### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @bienvenuushindi  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-03 17:43 UTC, merged